version: "3"

services:

  dscheduler:
    image: mc75/jupyter:v0.2
    ports:
     - "8786:8786"
     - "9786:9786"
     - "8787:8787"
    command: dask-scheduler
    networks:
      - distributed
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  dworker:
    image: mc75/jupyter:v0.2
    command: dask-worker dscheduler:8786
    environment:
      - "affinity:container!=dworker*"
    networks:
      - distributed
    depends_on:
      - dscheduler
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  notebook:
    image: mc75/jupyter:v0.2
    command: jupyter lab --allow-root --ip=0.0.0.0 --port=8888
    networks:
      - distributed
    hostname: notebook
    ports:
      - "8888:8888"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]


networks:
  distributed:
