FROM mc75/base:3.6-slim

RUN apt-get update && \
    apt-get install -y  --no-install-recommends libjasper libjasper-dev \
    libjpeg-dev libtiff5-dev libpng12-dev && \
    libilmbase12 \
    libopenexr22 \
    libgstreamer1.0-0 \
    libavcodec-extra57 \
    libavformat-dev \
    libilmbase12 \
    libavcodec-dev \
    libswscale-dev \
    libv4l-dev \
    libgtk2.0-dev \
    libgtk-3-dev \
    libxvidcore-dev \
    libx264-dev
