FROM mc75/base:3.6-slim

RUN apt-get update && \
    apt-get install -y  --no-install-recommends libjasper libjasper-dev &&\
    apt-get install -y  --no-install-recommends libjpeg-dev libtiff5-dev libpng12-dev && \
    apt-get install -y  --no-install-recommends libilmbase12 && \
    apt-get install -y  --no-install-recommends libopenexr22 && \
    apt-get install -y  --no-install-recommends libgstreamer1.0-0 && \
    apt-get install -y  --no-install-recommends libavcodec-extra57 && \
    apt-get install -y  --no-install-recommends libavformat-dev && \
    apt-get install -y  --no-install-recommends libilmbase12 && \
    apt-get install -y  --no-install-recommends libavcodec-dev && \
    apt-get install -y  --no-install-recommends libswscale-dev && \
    apt-get install -y  --no-install-recommends libv4l-dev && \
    apt-get install -y  --no-install-recommends libgtk2.0-dev && \
    apt-get install -y  --no-install-recommends libgtk-3-dev && \
    apt-get install -y  --no-install-recommends libxvidcore-dev && \
    apt-get install -y  --no-install-recommends libx264-dev
