FROM mc75/base:3.5-slim

RUN pip install --no-cache-dir \
    Cython==0.28.4 \
    bqplot==0.10.5 \
    bokeh==0.13.0 \
    bash-kernel==0.7.1 \
    ipykernel==4.8.2 \
    ipyparallel==6.2.2 \
    ipython==6.4.0 \
    ipython-genutils==0.2.0 \
    ipywidgets==7.3.0 \
    jupyter==1.0.0 \
    jupyter-client==5.2.3 \
    jupyter-console==5.2.0 \
    jupyter-core==4.4.0 \
    jupyterlab==0.32.1 \
    jupyterlab-launcher==0.10.5 \
    matplotlib==2.2.2 \
    notebook==5.6.0 \
    dask==0.18.1
